name: life
description: An attempt to take controll of my life in a better way
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  auto_route: ^2.4.2
  graphview: ^1.0.0
  freezed: ^0.14.3
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  permission_handler: ^8.1.6
  path_provider: ^2.0.0
  path: ^1.8.0
  flutter_svg: ^0.22.0
  external_path: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  intl_utils: ^2.4.0
  auto_route_generator: ^2.4.1
  flutter_launcher_icons: 0.9.2

# flutter pub run flutter_launcher_icons:main -f pubspec.yaml
flutter_icons:
  image_path: "assets/launcher/icon_legacy.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/launcher/icon_back.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/icon_front.png" # only available for Android 8.0 devices and above  

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: fa  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-Black.ttf
          weight: 900
    - family: Estedad-FD
      fonts:
        - asset: assets/fonts/Estedad-FD-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-FD-Black.ttf
          weight: 900

