name: life
description: An attempt to take controll of my life in a better way
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  intl_utils: ^2.4.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: fa

