name: life
description: An attempt to take controll of my life in a better way
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  auto_route: 2.2.0
  graphview: ^1.0.0
  freezed: ^0.14.3
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  intl_utils: ^2.4.0
  auto_route_generator: 2.1.0

dependency_overrides:
  meta: 1.4.0
  source_gen: 1.0.0
  analyzer: 1.7.0  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-Black.ttf
          weight: 900
    - family: Estedad-FD
      fonts:
        - asset: assets/fonts/Estedad-FD-Thin.ttf
          weight: 200
        - asset: assets/fonts/Estedad-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Estedad-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad-FD-Black.ttf
          weight: 900


flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: fa

